shadow = true;
shadow-radius = 8;
shadow-offset-x = -6;
shadow-offset-y = -6;

fading = false;

frame-opacity = 1.0;

corner-radius = 0;

backend = "xrender";

vsync = true;
use-damage = true;

detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;

dbus = true;

rules: (
{
match = "window_type = 'tooltip'";
shadow = true;
opacity = 0.95;
fade = false;
},
{
match = "window_type = 'dock' || window_type = 'desktop'";
shadow = false;
corner-radius = 0;
},
{
match = "class_g = 'i3bar'";
shadow = false;
},
{
match = "_GTK_FRAME_EXTENTS@";
shadow = false;
},
{
match = "class_g = 'Conky' || class_g ?= 'Notify-osd'";
shadow = false;
}
);

