[window]
padding = { x = 8, y = 8 }

[font]
size = 16

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[cursor]
style = { shape = "Underline", blinking = "Off" }

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black   = "#000000"
red     = "#555555"
green   = "#777777"
yellow  = "#999999"
blue    = "#aaaaaa"
magenta = "#bbbbbb"
cyan    = "#dddddd"
white   = "#ffffff"

[colors.bright]
black   = "#444444"
red     = "#666666"
green   = "#888888"
yellow  = "#aaaaaa"
blue    = "#bbbbbb"
magenta = "#cccccc"
cyan    = "#eeeeee"
white   = "#ffffff"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
