CompileFlags:
  BuiltinHeaders: QueryDriver

Index:
  Background: Build
  StandardLibrary: true

Completion:
  AllScopes: Yes
  ArgumentLists: FullPlaceholders
  HeaderInsertion: IWYU
  CodePatterns: All

Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    FastCheckFilter: Strict

InlayHints:
  Enabled: true
  ParameterNames: true
  DeducedTypes: true
  Designators: true